### ISSUE TITLE
如何编译edk2

### ISSUE THREAD

**Issue by wangzhankun** [yangxiaojuan-loongson/qemu-binary#2]
你好，我看您提供的文件成功编译了QEMU-efi。但是我尝试按照 

https://www.qemu.org/docs/master/system/loongarch/loongson3.html?highlight=loongarch

教程进行编译edk2时，提示没有loongson.des这个文件，请问应该怎么解决呀？

另外教程中的loongson/edk2-LoongarchVirt这个仓库已经找不到了，我是用的最新的官方edk2的库编译的。

**Comment by gaosong-loongson** [comment]
参考：
https://github.com/loongson/edk2-platforms/blob/master/Platform/Loongson/LoongArchQemuPkg/Readme.md

注意：
edk2  edk2-non-osi  edk2-platforms 下载到同级目录。Readme.md 写的不是很正确。

**Comment by wangzhankun** [comment]
好的，编译成功了，感谢。
